### ISSUE TITLE
Cannot Redeem Using DAO to DAO Generic Action

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1018]
Trying to redeem a proposal from another DAO, and getting an error: http://prntscr.com/opabhi

DAOfund manager passed a proposal to grant DAOfund rep, it passed.

Right now I am trying to redeem that proposal via DAOfund's GenesisProtocol scheme. I am getting an instant error when I try to redeem. 

here is console error: http://prntscr.com/opaceh

**Comment by arsena21** [comment]
Here is some more detail....

http://prntscr.com/oq5k1m
http://prntscr.com/oq5k6h
http://prntscr.com/oq5k9u

Or here for the entire thread: https://github.com/daostack/arc/issues/654

**Comment by jellegerbrandy** [comment]
@arsena21 , we think this is fixed, please re-open this issue if there are still problems

**Comment by arsena21** [comment]
This is still not fixed. Here is an example:

I submitted this proposal to redeem (Genesis DAO redeems a proposal from DAOfund): https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x383f6b963bded059dabcfaa82552ab45914301006417805a0db166f884cf015e

This is the original proposal in DAOfund giving rep to Genesis DAO: https://alchemy.daostack.io/dao/0xe8e1d0f1783b22ff409deb14fa5acc9cce2a3d15/proposal/0x8d9963c78692c9aacd99a67c16510872a769f37f30da6601237138342028b723

There is no reputation given to Genesis DAO.

**Comment by dkent600** [comment]
OK, my bad, was confusing this with another ticket.  This has not, in fact, been addressed yet.

**Comment by dkent600** [comment]
Following up here:  https://daostack.tpondemand.com/entity/1555-can-not-redeem-dao-to-dao

**Comment by arsena21** [comment]
I can’t see anything when I click on that link. Is there some way to share a public facing doc?

**Comment by dkent600** [comment]
This github page is the public-facing doc.  That link is to our internal process.

**Comment by dkent600** [comment]
@arsena21 I think there is a work-around for this.  Go to [here on etherscan.io](https://etherscan.io/address/0x332b8c9734b4097de50f302f7d9f273ffdb45b84#writeContract) and run this:

![image](https://user-images.githubusercontent.com/1821666/63625321-4221f500-c5cd-11e9-9d6a-82c09322319e.png)

ie:

```
redeem(
0x8d9963c78692c9aacd99a67c16510872a769f37f30da6601237138342028b723,
0x294f999356ed03347c7a23bcbcf8d33fa41dc830
)
```

Where the first argument is the id of the proposal that awards the rep and the second argument is the address of the Genesis Alpha avatar that is the beneficiary of the rep.

Let me know if that doesn't work or you would like me to run it for you.

**Comment by arsena21** [comment]
thanks for the info.

Just tried it, no rep is showing up for the beneficiary...

Cheers,
Eric

**Comment by arsena21** [comment]
Just curious, what is the contract for the etherscan address you sent? (
https://etherscan.io/address/0x332b8c9734b4097de50f302f7d9f273ffdb45b84#writeContract
)

**Comment by dkent600** [comment]
I am not seeing any events on that contract to suggest that redeem redeemed anything.

The address is the GenesisProtocol for both of the DAOs involved.

**Comment by dkent600** [comment]
I do see this transaction:  https://etherscan.io/tx/0x364400cb353f582fb1c4b57d28e73f57098b529d5402a48d10cacff2edcbf65a

**Comment by dkent600** [comment]
Hmmm, I think I may understand the problem.  You are trying to redeem rewards from ContributionReward using GenesisProtocol, but that is not how it works.  To do that you have to redeem  from ContributionReward, and to do that you have to go into DAOfund and redeem on behalf of Genesis Alpha.

**Comment by dkent600** [comment]
Sorry I honestly don't know how to do this in Alchemy.  But you can again work-around in the meantime.

Go to ethersan.io again, [this time here](https://etherscan.io/address/0x08cc7bba91b849156e9c44ded51896b38400f55b#writeContract).

Submit the form like this:

![image](https://user-images.githubusercontent.com/1821666/63637156-37a44180-c647-11e9-92ce-19ed2840d945.png)

The avatar address is DAOfund.  You will be asking for all possible rewards from ContributionReward.

Let me know how it goes.

**Comment by dkent600** [comment]
@arsena21 It may be that, in Alchemy, if you simply redeem on ContributionReward for yourself it will automatically redeem for Genesis Alpha.  Try that first....

**Comment by dkent600** [comment]
@arsena21 If the above doesn't work, you can try the following work-around.

Go to ethersan.io again, [this time here](https://etherscan.io/address/0x08cc7bba91b849156e9c44ded51896b38400f55b#writeContract).

Submit the form like this:

![image](https://user-images.githubusercontent.com/1821666/63637204-f82a2500-c647-11e9-8c90-597f85b20859.png)

The avatar address is DAOfund.  You will be asking for all possible rewards from ContributionReward.

Let me know how it goes.

**Comment by jellegerbrandy** [comment]
For any new proposals, this has been fixed in https://github.com/daostack/alchemy/pull/1083/files, and should be deployed to production in the in the next release. Thanks @arsena21 !

**Comment by arsena21** [comment]
Amazing :)

Thanks!!
