### ISSUE TITLE
Hovering over redeem button crashed the app O_O

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#503]
https://daostack-alchemy-staging.herokuapp.com/dao/0x15354e4aa3ee99bd07bb0b660fabf885c413033e/proposal/0xc5f35f687f1787d71913947b3fabd4fa81d56d8850fa471ed59a33450769d675

<img width="1386" alt="Screenshot 2019-03-26 at 21 17 56" src="https://user-images.githubusercontent.com/302774/55027048-ff072a00-500c-11e9-9963-118fbe4750ba.png">

**Comment by tibetsprague** [comment]
i think the bug with the redeem button is related to a DAO staking bounty, which doesnt seem to exist on the test DAO locally
seems like something we should have for the test DAO, to test

**Comment by A-Zak** [comment]
@jellegerbrandy Can you confirm that local daos don't have the DAO staking bounty?
if so, can we add some? :)

**Comment by jellegerbrandy** [comment]
I do not confirm. Parameters (I think) are these: https://github.com/daostack/migration/blob/master/migration-params.json, there is the DAO staking bounty. Can you tell me why you think it "does not seem to exist"? And make an issue in the migration repo and assign it to ben?

In any case, the app should not crash in any cases, so this issue remains open.

**Comment by tibetsprague** [comment]
The crashing should be fixed. Pending testing on staging 

Sent by m

**Comment by A-Zak** [comment]
@tibetsprague - is staging running your latest fix (this still happens on staging)?

If this helps, I'm using this account: 0x4F3EDF983AC636A65A842CE7C78D9AA706D3B113BCE9C46F30D7D21715B23B1D

**Comment by dkent600** [comment]
@A-Zak how do you get an account address so long?

**Comment by tibetsprague** [comment]
@A-Zak I dont think it has been pushed yet, again let's touch base tomorrow about how/when to update staging and let others know what is there

**Comment by A-Zak** [comment]
@tibetsprague fyi, I don't know if it has been deployed to staging yesterday or not, but this did happen to me today......

**Comment by tibetsprague** [comment]
@A-Zak can you tell me which proposal? and which user you are logged in as?

**Comment by A-Zak** [comment]
This only happens to me on my personal account: `0x6d1a4be65723355a9f5b12c446780a5000849461`
On this proposal: https://daostack-alchemy-staging.herokuapp.com/dao/0xaa6126527840b0079c6115e21097123220d1a48f/proposal/0x6af29dd2b9b1158976b377161c01cacf9cb40ad8fd716f89a0ac6efcebb6295d

Also, not sure if related, but still - I did notice that one of our test accounts (0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1) has some redemptions that cannot be redeemed. on `test take over` - the tx passes but nothing happens, and for the other two the tx simply fail.

**Comment by tibetsprague** [comment]
need to figure out how i can reproduce this...

**Comment by tibetsprague** [comment]
@A-Zak do you know what redemptions your user should have for that proposal?

**Comment by A-Zak** [comment]
does this help?
```{
  "data": {
    "proposal": {
      "__typename": "Proposal",
      "accountsWithUnclaimedRewards": [
        "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1",
        "0x6d1a4be65723355a9f5b12c446780a5000849461"
      ],
      "activationTime": "0",
      "boostedAt": null,
      "boostedVotePeriodLimit": "600",
      "confidenceThreshold": "0",
      "contributionReward": {
        "__typename": "ContributionRewardProposal",
        "beneficiary": "0x6d1a4be65723355a9f5b12c446780a5000849461",
        "ethReward": "0",
        "externalToken": "0x0000000000000000000000000000000000000000",
        "externalTokenReward": "0",
        "nativeTokenReward": "0",
        "periodLength": "12",
        "periods": "1",
        "reputationReward": "1000000000000000000"
      },
      "createdAt": "1554215404",
      "dao": {
        "__typename": "DAO",
        "id": "0xaa6126527840b0079c6115e21097123220d1a48f"
      },
      "daoBountyConst": "10",
      "description": "sdlkfj",
      "descriptionHash": "QmUygDHPsNTAXswv2tQZCeKEcALPdwCgD3UsVedg68TfHS",
      "executedAt": "1554217384",
      "executionState": "QueueTimeOut",
      "expiresInQueueAt": "1554217204",
      "gpRewards": [
        {
          "__typename": "GPReward",
          "id": "0x10599611d9cd9868c17c3e7544f35772602ccb7b3122b480604fd78f7c30003e"
        },
        {
          "__typename": "GPReward",
          "id": "0x37ce6b5f15c0dd48b05de077674257c93970986c984a2f231a1b57660021dfd6"
        }
      ],
      "id": "0x6af29dd2b9b1158976b377161c01cacf9cb40ad8fd716f89a0ac6efcebb6295d",
      "minimumDaoBounty": "100000000000",
      "organizationId": "0x3b54f5866f1b9b24c0ec5be06929d64d38b0eac1a6a6ab08c49ea8a625d58a75",
      "paramsHash": "0x3ceacc511ca924f65fad3efae4f9892773f73fa9e5eec1d65b029f81826dd3d9",
      "preBoostedAt": null,
      "preBoostedVotePeriodLimit": "600",
      "proposer": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1",
      "proposingRepReward": "5000000000",
      "queuedVotePeriodLimit": "1800",
      "queuedVoteRequiredPercentage": "50",
      "quietEndingPeriod": "300",
      "quietEndingPeriodBeganAt": null,
      "stage": "ExpiredInQueue",
      "stakes": [
        {
          "__typename": "ProposalStake",
          "id": "0x7638cdb7fde304ebf9ef6a7be18eb47ef8486bd8a2e42ea9b7b83f0bfd8fa7f6"
        }
      ],
      "stakesAgainst": "100000000000",
      "stakesFor": "10000000000000000",
      "thresholdConst": "2199023255552",
      "title": "sdlkfj",
      "totalRepWhenExecuted": "5990000000000000000000",
      "url": "",
      "votersReputationLossRatio": "1",
      "votes": [],
      "votesAgainst": "0",
      "votesFor": "0",
      "votingMachine": "0x08cc7bba91b849156e9c44ded51896b38400f55b",
      "winningOutcome": "Fail"
    }
  }
}```

**Comment by tibetsprague** [comment]
Yes that helps, thanks!

**Comment by A-Zak** [comment]
These are the two gpRewards:

```{
  "data": {
    "gpreward": {
      "beneficiary": "0x6d1a4be65723355a9f5b12c446780a5000849461",
      "createdAt": "1554217384",
      "dao": {
        "id": "0xaa6126527840b0079c6115e21097123220d1a48f"
      },
      "daoBountyForStaker": null,
      "daoBountyForStakerRedeemedAt": "0",
      "id": "0x10599611d9cd9868c17c3e7544f35772602ccb7b3122b480604fd78f7c30003e",
      "proposal": {
        "id": "0x6af29dd2b9b1158976b377161c01cacf9cb40ad8fd716f89a0ac6efcebb6295d"
      },
      "reputationForProposer": null,
      "reputationForProposerRedeemedAt": "0",
      "reputationForVoter": null,
      "reputationForVoterRedeemedAt": "0",
      "tokenAddress": "0x543ff227f64aa17ea132bf9886cab5db55dcaddf",
      "tokensForStaker": "10000000000000000",
      "tokensForStakerRedeemedAt": "0"
    }
  }
}```

```{
  "data": {
    "gpreward": {
      "beneficiary": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1",
      "createdAt": "1554217384",
      "dao": {
        "id": "0xaa6126527840b0079c6115e21097123220d1a48f"
      },
      "daoBountyForStaker": null,
      "daoBountyForStakerRedeemedAt": "0",
      "id": "0x37ce6b5f15c0dd48b05de077674257c93970986c984a2f231a1b57660021dfd6",
      "proposal": {
        "id": "0x6af29dd2b9b1158976b377161c01cacf9cb40ad8fd716f89a0ac6efcebb6295d"
      },
      "reputationForProposer": null,
      "reputationForProposerRedeemedAt": "0",
      "reputationForVoter": null,
      "reputationForVoterRedeemedAt": "0",
      "tokenAddress": "0x543ff227f64aa17ea132bf9886cab5db55dcaddf",
      "tokensForStaker": null,
      "tokensForStakerRedeemedAt": "0"
    }
  }
}```
